# Dependencies
markdown: redcarpet
hightlighter: pygments
gems: [jekyll-paginate]

# Permalinks
permalink: pretty

# Setup
title: MakerGirl
tagline: Today’s makers. <br> Tomorrow’s life changers.
description: MakerGirl is a program led by University of Illinois students that educates 7-10 year old girls on STEM (Science, Technology, Engineering, Mathematics) fields through 3-D printing workshops at the College of Business MakerLab, creative activities, and lessons on leading women in STEM fields.
keywords: MakerGirl, UIUC, Illinois, 3D, Printing, Engineering, STEM
url: http://makergirl.us
baseurl: /
paginate: 5
paginate_path: 'blog/page:num'
paginate_base: '/blog/'
sass:
  style: :compressed

# Social Media
facebook: https&#58;//www.facebook.com/makergirlofficial
twitter: https&#58;//twitter.com/_MakerGirl
instagram: https&#58;//www.instagram.com/_MakerGirl/
linkedin: https&#58;//www.linkedin.com/company/makergirl
youtube: https&#58;//www.youtube.com/channel/UCbaoZ7g-5RYXhDFtYiulkog/feed

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - divshot.json
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Author
author:
  name: Joseph Milla
  url: https://twitter.com/josephmilla
  email: joseph@milla.xyz

# Version
version: 0.0.0
