# Dependencies
markdown: redcarpet
hightlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: MakerGirl
tagline: Plastic isn't just for Barbies<sup>&#174;</sup>
description: MakerGirl is a program led by University of Illinois students that educates 7-10 year old girls on STEM (Science, Technology, Engineering, Mathematics) fields through 3-D printing workshops at the College of Business MakerLab, creative activities, and lessons on leading women in STEM fields.
keywords: MakerGirl, UIUC, Illinois, 3D, Printing, Engineering, STEM
url: http://www.makergirl.us
baseurl: /
paginate: 5
paginate_path: 'blog/page:num'
paginate_base: '/blog/'
sass:
  style: :compressed

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Author
author:
  name: Joseph Milla
  url: https://twitter.com/josephmilla
  email: hello@josephmilla.com

# Version
version: 0.0.0
