- value: Communicate candidly through thick and thin!
- value: Be enthusiastic and passionate! Positivity is contagious.
- value: Changemakers exceed expectations.
- value: Make the game so big that failure is inevitable, and when failure happens, celebrate it.
- value: Enjoy constraints - value&#58; they drive creativity.
- value: Be accountable for your work. Have integrity.
- value: Roll up your sleeves and get involved with every aspect of MakerGirl. Everyone should be accessible every day.
- value: Don’t wait for someone to tell you what to do. Take initiative, and make it so good that they can’t refuse.
- value: No idea is too large, wild, or small; however, ideas are a commodity, and execution of them is not.
- value: WE ARE ALL FOUNDERS OF MakerGirl - value&#58; so make your mark.
